### ISSUE TITLE
hardware to read eec

### ISSUE THREAD

**Issue by fmcwb** [flxkrmr/eec-iv-reader-arduino#1]
Hi flxkrmr,

what hardware are you using to test the eec-iv protocol? I have arduino mega 2560 for use, to using more UARTS... 

I see you using the tft display... I intend to use the serial to handle the read data.

Thank You.

**Comment by flxkrmr** [comment]
Hi,
currently I am using a Arduino uno attached to a rs485 board. As the uno only has one serial modul I wanted to attach a display to get some reading. But over the time I switched to using arduinos software serial as it is easier to time right for the eec iv ecu. This is why I also switched back to usb-serial output for debugging.
At the moment this is still in a very early development stage and thats why I don't want to add any circuits or manuals on how to set this up (yet). But as you can see in the main ino file, these are the pins that I currently use for the RS485 module:

```
static const int DI=3;
static const int RE=6;
static const int RO=2;
```
