### ISSUE TITLE
UART Message format array length number of bytes correct?

### ISSUE THREAD

**Issue by mercury64** [flxkrmr/eec-iv-reader-arduino#24]
UART messages are 11 bytes long, why is the CART::startMessage 18 bytes?

**Comment by flxkrmr** [comment]
Thanks for your interest in the project!

The start message differs from all other messages. I could not find anything about it in the docs, but used the infos in this project: https://github.com/babroval/ford-eec-iv-diagnostic/blob/master/DCL_communication_map.pdf (see blue message on the left). After sending this message the ECU goes into "DCL-communication-mode" and start sending the sync messages. What is weird, the start message is send with 2400 baud and the ECU starts sending sync messages with 9600 baud

**Comment by flxkrmr** [comment]
Implemented in 452906b2bd2ff4d2686d64f7763628f636d0f63c
