### ISSUE TITLE
Need to implement parity check for CART messages

### ISSUE THREAD

**Issue by mercury64** [flxkrmr/eec-iv-reader-arduino#26]
Only 12-bits of the 16-bit word are data.
The upper nibble is the parity check value(4-bits) of the 16-bit word.
Data words are stored as LSB, MSB.

To do the parity check, XOR each nibble with the value 0xA.
Examples:
Data: 
00 A0 01 B0 00 00 
00 B1 FF 5F 00 00 
00 82 26 A4 00 00 
00 93 00 A0 00 00 
LSB   MSB = MSBLSB = N4 N3N2N1= N3 ^ N2 ^ N1 ^ 0xA = N4
0x00 0xA0 = 0xA000 = A 000 = 0 ^ 0 ^ 0 ^ A= A
0x01 0xB0 = 0xB001 = B 001 = 0 ^ 0 ^ 1 ^ A = B
0x00 0xB1 = 0xB100 = B 100 = 1 ^ 0 ^ 0 ^ A = B
0xFF 0x5F = 0x5FFF = 5 FFF = F ^ F ^ F ^ A = 5
0x00 0x82 = 0x8200 = 8 200 = 2 ^ 0 ^ 0 ^ A = 8
0x26 0xA4 = 0xA426 = A 426 =4 ^ 2 ^ 6 ^ A = A
0x00 0x93 = 0x9300 = 9 300 = 3 ^ 0 ^ 0 ^ A = 9

**Comment by flxkrmr** [comment]
Thanks for the advise. Implemented in 94a1510002c5f7a70247f492855029cc2a429d2c
